# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mmoras@student.42heilbronn.de <mmoras>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/10/15 18:19:16 by mmoras@stud       #+#    #+#              #
#    Updated: 2025/10/17 17:05:44 by mmoras@stud      ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

MAKEFLAGS += -r
CC = gcc
CFLAGS = 
COMPILE = $(CC) $(CFLAGS)

OBJDIR = obj
BINDIR = bin
HEADER = ../libft/libft.h

SRCS = $(wildcard *.c)
OBJS = $(SRCS:.c=.o)
NAME = tester


all:
	echo $(NAME)
